replace=input("Enter A Sentence")
print("Computing" * 15)
print("Compute Complete")
a=replace.replace("a","*")
b=replace.replace("e","*")
c=replace.replace("i","*")
d=replace.replace("o","*")
e=replace.replace("u","*")
print(a, b, c, d, e)
